### ISSUE TITLE
Why is there no composer support?

### ISSUE THREAD

**Issue by BorislavSabev** [localgod/pecl_mongo_phpdoc#2]
Hey, first off heads up for the good and useful work. Nice one! :+1: 
  However, why is there no composer support such that one could install this "package" or meta-package as a dev dependency?

It'd be a nice feature. Also I'd be willing to lend a hand with it.

Will be waiting for your answer. 
Cheers!

**Comment by localgod** [comment]
Composer support added:
https://packagist.org/packages/localgod/pecl_mongo_phpdoc
